annotationAutodiscovery:
  collector: alloy-metrics
  enabled: true
applicationObservability:
  collector: alloy-singleton
  destinations:
    - grafana-cloud-metrics
    - grafana-cloud-logs
    - grafana-cloud-traces
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
cluster:
  name: o11y-cluster
clusterEvents:
  collector: alloy-singleton
  enabled: true
clusterMetrics:
  collector: alloy-metrics
  enabled: true
collectorCommon:
  alloy:
    remoteConfig:
      auth:
        password: "${GRAFANA_CLOUD_ACCESS_TOKEN}"
        type: basic
        username: "${GRAFANA_FLEET_USERNAME}"
      enabled: true
      url: https://fleet-management-prod-012.grafana.net
collectors:
  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset
  alloy-metrics:
    presets:
      - clustered
      - statefulset
  alloy-singleton:
    presets:
      - singleton
    customConfig: |
      otelcol.connector.servicegraph "default" {
        metrics_flow_default_histogram_boundaries = [0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10]

        output {
          metrics = [
            otelcol.exporter.otlp.grafana_metrics.input,
          ]
        }
      }
costMetrics:
  collector: alloy-metrics
  enabled: true
destinations:
  grafana-cloud-logs:
    auth:
      password: "${GRAFANA_CLOUD_ACCESS_TOKEN}"
      type: basic
      username: "${GRAFANA_LOGS_USERNAME}"
    type: loki
    url: https://logs-prod-018.grafana.net./loki/api/v1/push
  grafana-cloud-metrics:
    auth:
      password: "${GRAFANA_CLOUD_ACCESS_TOKEN}"
      type: basic
      username: "${GRAFANA_METRICS_USERNAME}"
    type: prometheus
    url: https://prometheus-prod-32-prod-ca-east-0.grafana.net./api/prom/push
  grafana-cloud-traces:
    auth:
      password: "${GRAFANA_CLOUD_TRACES_TOKEN}"
      type: basic
      username: "${GRAFANA_TRACES_USERNAME}"
    logs:
      enabled: false
    metrics:
      enabled: false
    traces:
      enabled: true
    type: otlp
    url: https://tempo-prod-13-prod-ca-east-0.grafana.net:443
hostMetrics:
  collector: alloy-metrics
  enabled: true
  energyMetrics:
    enabled: true
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true
nodeLogs:
  collector: alloy-logs
  enabled: true
podLogsViaLoki:
  collector: alloy-logs
  enabled: true
telemetryServices:
  kepler:
    deploy: true
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  opencost:
    deploy: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: o11y-cluster
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-32-prod-ca-east-0.grafana.net./api/prom
  windows-exporter:
    deploy: true