apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-public
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
  selector:
    app: nginx

#   Allows the following:
#   kubectl port-forward nginx-prometheus-5969fc9877-l5wm6 9113:9113      